spring:

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/photogram
    username: root
    password: 1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

file:
  path: /Users/bobby/Desktop/kim/study/upload/