spring:

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/photogram
    username: root
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html

  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 340840187451921
            client-secret: 995897862ab58dee141b8647c188ce90
            scope:
            - public_profile
            - email


file:
  path: /Users/bobby/Desktop/kim/study/upload/
#  path: C:\Users\Woojin\Desktop\study\photogram-image\